
stages:
  - deploy

variables:
  AWS_DEFAULT_REGION: us-west-2b
  BUCKET_NAME: dev.cryptoping.com

deployDev:
  only:
    - dev@cryptoping/cryptoping-lander
  image: "python:latest"  # We use python because there is a well-working AWS Sdk
  stage: deploy
  before_script:
    - pip install awscli # Install the SDK
  script:
    - aws s3 cp ./dist s3://${BUCKET_NAME}/${CI_COMMIT_REF_SLUG} --recursive # Replace example-bucket with your bucket
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    url: http://${BUCKET_NAME}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com/${CI_COMMIT_REF_SLUG}  # This is the url of the bucket we saved before
    on_stop: clean_s3 # When the branch is merged, we clean up after ourself

clean_s3:
  image: "python:latest"
  stage: deploy
  before_script:
    - pip install awscli
  script:
    - aws s3 rm s3://${BUCKET_NAME}/${CI_COMMIT_REF_SLUG} --recursive # Replace example-bucket with your bucket
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    action: stop
  when: manual
