variables:
  AWS_DEFAULT_REGION: us-west-2

.deploy_to_s3:  # `.` ignores the script
  image: "python:latest"
  stage: deploy
  before_script:
    - pip install awscli
    - echo BUCKET_NAME:${BUCKET_NAME}
    - echo CI_COMMIT_REF_SLUG:${CI_COMMIT_REF_SLUG}
  script:
    - aws s3 sync ./dist s3://${BUCKET_NAME} --recursive
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    url: https://${BUCKET_NAME}

deploy_dev:
  extends: .deploy_to_s3
  only:
    - dev
  variables:
    BUCKET_NAME: dev.cryptoping.com

deploy_master:
  extends: .deploy_to_s3
  only:
    - master
  variables:
    BUCKET_NAME: cryptoping.com
